# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update Site

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '15 */6 * * *'
    

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run painter
      run: |
        python painter.py
    - name: Create html
      run: |
        python createhtml.py
    - name: Git commit
      uses: stefanzweifel/git-auto-commit-action@v5




